INSERT INTO QuestionSet (id,decsription) VALUES (1,'test question set');

INSERT INTO Question (id,questionText,questionSet) VALUES (1,'Which team is the current NBA title owner?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (2,'Which countries are from Europe?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (3,'When did Bram Stoker wrote Dracula?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (4,'Who is the fastest man on earth?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (5,'What colors are in Italian flag?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (6,'How many oscars did Pulp Fiction won?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (7,'In which 1979 film was the spaceship called Nostromo?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (8,'Which TV character said, "Live long and prosper"?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (9,'Which is the best selling beer in the world?',1);
INSERT INTO Question (id,questionText,questionSet) VALUES (10,'Which are Java ORM frameworks?',1);

INSERT INTO Answer (id,answerText,correct,question) VALUES (1,'Spurs',1,1);
INSERT INTO Answer (id,answerText,correct,question) VALUES (2,'Bulls',0,1);
INSERT INTO Answer (id,answerText,correct,question) VALUES (3,'Heat',0,1);
INSERT INTO Answer (id,answerText,correct,question) VALUES (4,'Lakers',0,1);
INSERT INTO Answer (id,answerText,correct,question) VALUES (5,'Columbia',0,2);
INSERT INTO Answer (id,answerText,correct,question) VALUES (6,'Ukraine',1,2);
INSERT INTO Answer (id,answerText,correct,question) VALUES (7,'France',1,2);
INSERT INTO Answer (id,answerText,correct,question) VALUES (8,'Chile',0,2);
INSERT INTO Answer (id,answerText,correct,question) VALUES (9,'1902',0,3);
INSERT INTO Answer (id,answerText,correct,question) VALUES (10,'1846',0,3);
INSERT INTO Answer (id,answerText,correct,question) VALUES (11,'1896',1,3);
INSERT INTO Answer (id,answerText,correct,question) VALUES (12,'1880',0,3);
INSERT INTO Answer (id,answerText,correct,question) VALUES (14,'Arjen Robben',0,4);
INSERT INTO Answer (id,answerText,correct,question) VALUES (15,'Yohan Blake',0,4);
INSERT INTO Answer (id,answerText,correct,question) VALUES (16,'Usain Bolt',1,4);
INSERT INTO Answer (id,answerText,correct,question) VALUES (17,'Blue',0,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (18,'White',1,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (19,'Pink',0,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (20,'Red',1,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (21,'Green',1,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (22,'Black',0,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (23,'Yellow',0,5);
INSERT INTO Answer (id,answerText,correct,question) VALUES (24,'1',1,6);
INSERT INTO Answer (id,answerText,correct,question) VALUES (25,'2',0,6);
INSERT INTO Answer (id,answerText,correct,question) VALUES (26,'3',0,6);
INSERT INTO Answer (id,answerText,correct,question) VALUES (27,'4',0,6);
INSERT INTO Answer (id,answerText,correct,question) VALUES (28,'Close encounters of the third kind',0,7);
INSERT INTO Answer (id,answerText,correct,question) VALUES (29,'2011 space odyssey',0,7);
INSERT INTO Answer (id,answerText,correct,question) VALUES (30,'Alien',1,7);
INSERT INTO Answer (id,answerText,correct,question) VALUES (31,'Captain Kirk',0,8);
INSERT INTO Answer (id,answerText,correct,question) VALUES (32,'Captain America',0,8);
INSERT INTO Answer (id,answerText,correct,question) VALUES (33,'Spock',1,8);
INSERT INTO Answer (id,answerText,correct,question) VALUES (34,'Tarzan',0,8);
INSERT INTO Answer (id,answerText,correct,question) VALUES (35,'Bud light (USA)',0,9);
INSERT INTO Answer (id,answerText,correct,question) VALUES (36,'Snow (China)',1,9);
INSERT INTO Answer (id,answerText,correct,question) VALUES (37,'Corona (Mexico)',0,9);
INSERT INTO Answer (id,answerText,correct,question) VALUES (38,'Heineken (Netherlands)',0,9);
INSERT INTO Answer (id,answerText,correct,question) VALUES (39,'Slick',0,10);
INSERT INTO Answer (id,answerText,correct,question) VALUES (40,'Hibernate',1,10);
INSERT INTO Answer (id,answerText,correct,question) VALUES (41,'MyBatis',1,10);
INSERT INTO Answer (id,answerText,correct,question) VALUES (42,'Apache Shiro',0,10);